version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase...
      #- mvn clean package
      #- mvn liquibase:update
      - echo Specifically Rollback for removing the 500 internal server error
      - mvn liquibase:rollback -Dliquibase.rollbackCount 3

  post_build:
    commands:
      - echo Build Completed Succesfully
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes
