version: 0.2
phases:
  build:
    commands:
      - echo Entered The Build Phase
      - mvn clean package
    post_build:
      commands:
        -echo Build Completed Succesfully
artifacts:
  files:
    - target/Oauth-service.jar
  discard-paths: yes
