version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - package get cleaned and repacked
      - mvn liquibase:changelogSync
      - mvn liquibase:update
  post_build:
    commands:
      - echo Build Completed Succesfully
artifacts:
  files:
    - target/OAuth-With-Google-0.0.1-SNAPSHOT.jar
  discard-paths: yes
